name: Daily Retraction Watch Updater

on:
  schedule:
    - cron: "0 23 * * *"  # Every day at 6 AM UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write credentials from GitHub Secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > credentials.json

      - name: Run script
        run: python update_retraction_watch.py